<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" total="6" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Jenkins TestRail Plugin" duration-ms="81" started-at="2016-02-22T18:42:17Z" finished-at="2016-02-22T18:42:17Z">
    <groups>
      <group name="TESTRAIL-123">
        <method signature="TestNGSuiteTest.testSetDuration_givenInvalidInteger_throw()[pri:0, instance:testrail.testrail.testng.TestNGSuiteTest@f79e]" name="testSetDuration_givenInvalidInteger_throw" class="testrail.testrail.testng.TestNGSuiteTest"/>
        <method signature="TestNGSuiteTest.testSetDuration_givenValidInteger_setValue()[pri:0, instance:testrail.testrail.testng.TestNGSuiteTest@f79e]" name="testSetDuration_givenValidInteger_setValue" class="testrail.testrail.testng.TestNGSuiteTest"/>
        <method signature="TestNGSuiteTest.testSetFinished()[pri:0, instance:testrail.testrail.testng.TestNGSuiteTest@f79e]" name="testSetFinished" class="testrail.testrail.testng.TestNGSuiteTest"/>
        <method signature="TestNGSuiteTest.testSetStarted()[pri:0, instance:testrail.testrail.testng.TestNGSuiteTest@f79e]" name="testSetStarted" class="testrail.testrail.testng.TestNGSuiteTest"/>
      </group> <!-- TESTRAIL-123 -->
    </groups>
    <test name="TestNG Result Model Creation" duration-ms="81" started-at="2016-02-22T18:42:17Z" finished-at="2016-02-22T18:42:17Z">
      <class name="testrail.testrail.testng.TestNGSuiteTest">
        <test-method status="PASS" signature="testSetDuration_givenInvalidInteger_throw()[pri:0, instance:testrail.testrail.testng.TestNGSuiteTest@f79e]" test-instance-name="" name="testSetDuration_givenInvalidInteger_throw" duration-ms="26" started-at="2016-02-22T12:42:17Z" finished-at="2016-02-22T12:42:17Z">
          <exception class="java.lang.NumberFormatException">
            <message>
              <![CDATA[For input string: "1asdf"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NumberFormatException: For input string: "1asdf"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at testrail.testrail.testng.TestNGSuite.setDuration(TestNGSuite.java:43)
	at testrail.testrail.testng.TestNGSuiteTest.testSetDuration_givenInvalidInteger_throw(TestNGSuiteTest.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NumberFormatException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSetDuration_givenInvalidInteger_throw -->
        <test-method status="PASS" signature="testSetDuration_givenValidInteger_setValue()[pri:0, instance:testrail.testrail.testng.TestNGSuiteTest@f79e]" test-instance-name="" name="testSetDuration_givenValidInteger_setValue" duration-ms="9" started-at="2016-02-22T12:42:17Z" finished-at="2016-02-22T12:42:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSetDuration_givenValidInteger_setValue -->
        <test-method status="FAIL" signature="testSetFinished()[pri:0, instance:testrail.testrail.testng.TestNGSuiteTest@f79e]" test-instance-name="" name="testSetFinished" duration-ms="6" started-at="2016-02-22T12:42:17Z" finished-at="2016-02-22T12:42:17Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Malformed date: 2016-02-18T15:41:01Z]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Malformed date: 2016-02-18T15:41:01Z
	at testrail.testrail.testng.TestNGSuite.setFinished(TestNGSuite.java:78)
	at testrail.testrail.testng.TestNGSuiteTest.testSetFinished(TestNGSuiteTest.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSetFinished -->
        <test-method status="FAIL" signature="testSetStarted()[pri:0, instance:testrail.testrail.testng.TestNGSuiteTest@f79e]" test-instance-name="" name="testSetStarted" duration-ms="0" started-at="2016-02-22T12:42:17Z" finished-at="2016-02-22T12:42:17Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Malformed date: 2016-02-18T15:41:01Z]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Malformed date: 2016-02-18T15:41:01Z
	at testrail.testrail.testng.TestNGSuite.setStarted(TestNGSuite.java:61)
	at testrail.testrail.testng.TestNGSuiteTest.testSetStarted(TestNGSuiteTest.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSetStarted -->
      </class> <!-- testrail.testrail.testng.TestNGSuiteTest -->
    </test> <!-- TestNG Result Model Creation -->
  </suite> <!-- Jenkins TestRail Plugin -->
  <suite name="Widget" duration-ms="9" started-at="2016-02-22T18:42:17Z" finished-at="2016-02-22T18:42:17Z">
    <groups>
    </groups>
    <test name="Widget Works" duration-ms="4" started-at="2016-02-22T18:42:17Z" finished-at="2016-02-22T18:42:17Z">
      <class name="testrail.testrail.TestWidgetWorks">
        <test-method status="PASS" signature="testVerifySomething_givenSomething_thenSomething()[pri:0, instance:testrail.testrail.TestWidgetWorks@68567e20]" name="testVerifySomething_givenSomething_thenSomething" duration-ms="2" started-at="2016-02-22T12:42:17Z" finished-at="2016-02-22T12:42:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testVerifySomething_givenSomething_thenSomething -->
      </class> <!-- testrail.testrail.TestWidgetWorks -->
    </test> <!-- Widget Works -->
    <test name="Widget Does X" duration-ms="2" started-at="2016-02-22T18:42:17Z" finished-at="2016-02-22T18:42:17Z">
      <class name="testrail.testrail.TestWidgetWorks">
        <test-method status="FAIL" signature="testVerifySomething_givenSomethingElse_thenSomethingElse()[pri:0, instance:testrail.testrail.TestWidgetWorks@672872e1]" name="testVerifySomething_givenSomethingElse_thenSomethingElse" duration-ms="2" started-at="2016-02-22T12:42:17Z" finished-at="2016-02-22T12:42:17Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at testrail.testrail.TestWidgetWorks.testVerifySomething_givenSomethingElse_thenSomethingElse(TestWidgetWorks.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testVerifySomething_givenSomethingElse_thenSomethingElse -->
      </class> <!-- testrail.testrail.TestWidgetWorks -->
    </test> <!-- Widget Does X -->
  </suite> <!-- Widget -->
</testng-results>
